---
title: "Mini-Project 2"
author: 
date: "2019-03-24"
output: 
  html_document:
    code_folding: show
---

## Loading the data


```{r, message=FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
candidates_data<-candidates %>%
  select(cand_id, cand_name, cand_election_yr,cand_party_affiliation) %>%
  filter(cand_election_yr=="2012")
```

```{r}
contributions_data<-contributions %>%
  select(cand_id,name,transaction_amt)
```

```{r}
candidate_contribution_join <- candidates_data %>%
  full_join(contributions_data, by="cand_id") 

```


```{r}
money_states<-candidate_contribution_join %>%
  filter(cand_party_affiliation=="DEM"|cand_party_affiliation=="REP") %>%
  group_by(cand_office_state,cand_party_affiliation) %>%
  summarise(total_amt=sum(abs(transaction_amt),na.rm=TRUE)) %>%
  filter(!cand_office_state %in% c("PR","US","VI","AS","GU","MP","DC"))
```

```{r}
ratio_function<-function(state_arg) {
  money_states %>%
    filter(cand_office_state == state_arg)%>%
  mutate(total = sum(total_amt),
ratio = (total_amt/total)*100)
}

map_ratio <- map_df(c("AK","AL", "AR","AZ", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"),ratio_function)
```

```{r}
map_ratio_order <- map_ratio %>%
  mutate(rep_percent = ifelse(
    cand_party_affiliation == "REP", 1, 0))%>%
  arrange(-rep_percent)
```

```{r}
ratio_plot <-ggplot(map_ratio_order, aes(x = fct_inorder(cand_office_state), 
                               y = ratio, 
                               fill = cand_party_affiliation))+
  geom_bar(stat="identity", position="fill")+
  scale_fill_manual(values = c("DEM" = "#0C25D4", "REP" = "#DC143C"))+
  theme_minimal() 

ratio_plot
```

Word count: `r wordcountaddin::word_count()`